---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    shell: /apache-tomcat-8.5.51/bin/shutdown.sh 
  - name: Clean the existing war file
    file:
      path: /apache-tomcat-8.5.51/webapps/gameoflife.war
      state: absent    
  - name: Deploy War File
    get_url:
       url: http://13.127.6.58:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife1&p=war&v=LATEST
       dest: /apache-tomcat-8.5.51/webapps/gameoflife.war
       notify: retsart tomcat
  handlers:
  - name: restart tomcat
  service: name=tomcat state=restarted
 
